### ISSUE TITLE
full json datasheet link is broken

### ISSUE THREAD

**Issue by cholin** [freifunk/openwifimap-html5#3]
If you click on "full json datasheet" at http://openwifimap.net/#detail?node=nkarcaden-fhain.olsr it will result in an "not-found" error. The app should use instead of http://openwifimap.net/db/nkarcaden-fhain.olsr the new api url: http://api.openwifimap.net/db/nkarcaden-fhain.olsr

**Comment by booo** [comment]
Problematic line:

https://github.com/freifunk/openwifimap-html5/blob/gh-pages/script/owm_app.js#L70

Request url should be api.open...
