### ISSUE TITLE
CloudMade Tiles are not free anymore, 403 for tile requests

### ISSUE THREAD

**Issue by guerda** [freifunk/openwifimap-html5#5]
The CloudMade tiles cannot be loaded anymore, as they are restricting their free tiles. In Firefox and Chrome, the map background is completely empty.
In Firebug the network tab shows the following:

| URL | Status | Domain | Size | Remote IP | Time |
| --- | --- | --- | --- | --- | --- |
| GET 10903.png | 403 Forbidden | a.tile.cloudmade.com | 12 B | 54.230.200.166:80 | 138ms |
| GET 10903.png | 403 Forbidden | b.tile.cloudmade.com | 12 B | 54.230.200.192:80 | 134ms |

Replacing CloudMade with an alternative tile provider could help, like Lyrk.de

**Comment by guerda** [comment]
Sorry for posting this bug. It seems that master is already updated to lyrk, but it is not deployed yet on freifunk rheinland.

**Comment by andrenarchy** [comment]
It's already deployed on http://openwifimap.net/. Can you provide the URL of the instance that is not yet updated?

**Comment by guerda** [comment]
I was confused, I thought http://map.freifunk-rheinland.net would be a mirror for openwifimap.net. The Map Freifunk is not yet updated. http://ffmap.freifunk-rheinland.net/ is updated, though...

**Comment by andrenarchy** [comment]
Do you know who operates this site? It would be great if you can file a bug at Freifunk Rheinland such that this can be fixed.

**Comment by guerda** [comment]
I dropped them a line. It seems that there are two versions of their map online, but only one works. Unfortunately, both contain a different data set than http://openwifimap.net.

**Comment by andrenarchy** [comment]
Thanks! Maybe they can drop one instance and let it sync with http://openwifimap.net.
